version: 2
jobs:
  deploy:
    docker:
      - image: circleci/php:7.2.9
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: echo $ENV | base64 --decode > .env

      - run: sudo composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: sudo php artisan key:generate

      - run: ./vendor/bin/phpunit tests/



      - run: ssh -o "StrictHostKeyChecking=no" $SSH_USER@$SSH_HOST "~/deploy.sh"

workflows:
  version: 2
  test:
    jobs:
      - deploy